// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc157.FRC2018;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.AnalogPotentiometer;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveRight1;
    public static SpeedController driveRight2;
    public static SpeedController driveLeft1;
    public static SpeedController driveLeft2;
    public static Encoder driveRightQuad;
    public static Encoder drivedriveLeftQuad;
    public static AnalogGyro driveGyro;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    @SuppressWarnings("deprecation")
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        
        
        driveRight1 = new Spark(1);
        
        
        driveRight2 = new Spark(2);
        
        
        driveLeft1 = new Spark(3);
        
        
        driveLeft2 = new Spark(4);
        
        
        driveRightQuad = new Encoder(2, 3, false, EncodingType.k4X);
        LiveWindow.addSensor("Drive", "driveRightQuad", driveRightQuad);
        driveRightQuad.setDistancePerPulse(0.052333);
        driveRightQuad.setPIDSourceType(PIDSourceType.kRate);
        drivedriveLeftQuad = new Encoder(0, 1, true, EncodingType.k4X);
        LiveWindow.addSensor("Drive", "driveLeftQuad", drivedriveLeftQuad);
        drivedriveLeftQuad.setDistancePerPulse(0.052333);
        drivedriveLeftQuad.setPIDSourceType(PIDSourceType.kRate);
        driveGyro = new AnalogGyro(0);
        LiveWindow.addSensor("Drive", "driveGyro", driveGyro);
        driveGyro.setSensitivity(0.007);


        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
